import type { Book, Customer } from './types';

export const DUMMY_BOOKS: Omit<Book, 'id'>[] = [
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    productionPrice: 7.5,
    sellingPrice: 16.99,
    stock: 50,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    productionPrice: 6.2,
    sellingPrice: 14.99,
    stock: 35,
  },
  {
    title: '1984',
    author: 'George Orwell',
    productionPrice: 8.0,
    sellingPrice: 15.99,
    stock: 60,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    productionPrice: 5.5,
    sellingPrice: 12.99,
    stock: 45,
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    productionPrice: 4.8,
    sellingPrice: 13.99,
    stock: 70,
  },
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    productionPrice: 6.8,
    sellingPrice: 14.49,
    stock: 25,
  },
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    productionPrice: 9.0,
    sellingPrice: 18.99,
    stock: 80,
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    productionPrice: 7.2,
    sellingPrice: 15.49,
    stock: 40,
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    productionPrice: 10.5,
    sellingPrice: 22.99,
    stock: 15,
  },
  {
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    productionPrice: 12.0,
    sellingPrice: 25.0,
    stock: 10,
  },
  {
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    productionPrice: 15.0,
    sellingPrice: 29.99,
    stock: 55,
  },
  {
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    productionPrice: 9.5,
    sellingPrice: 19.99,
    stock: 30,
  },
  {
    title: 'Ulysses',
    author: 'James Joyce',
    productionPrice: 11.0,
    sellingPrice: 24.99,
    stock: 20,
  },
  {
    title: 'The Odyssey',
    author: 'Homer',
    productionPrice: 8.5,
    sellingPrice: 17.99,
    stock: 65,
  },
  {
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    productionPrice: 9.8,
    sellingPrice: 20.99,
    stock: 38,
  },
  {
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    productionPrice: 8.9,
    sellingPrice: 18.49,
    stock: 48,
  },
];

export const DUMMY_CUSTOMERS: Omit<Customer, 'id'>[] = [
  {
    name: 'Alice Johnson',
    phone: '555-0101',
    whatsapp: '555-0101',
    address: '123 Maple St, Springfield',
    openingBalance: 50.0,
    dueBalance: 50.0,
  },
  {
    name: 'Bob Williams',
    phone: '555-0102',
    address: '456 Oak Ave, Shelbyville',
    openingBalance: 0,
    dueBalance: 0,
  },
  {
    name: 'Charlie Brown',
    phone: '555-0103',
    whatsapp: '555-0103',
    address: '789 Pine Ln, Capital City',
    openingBalance: 15.5,
    dueBalance: 15.5,
  },
  {
    name: 'Diana Prince',
    phone: '555-0104',
    address: '101 Themyscira Blvd, Gateway City',
    openingBalance: 0,
    dueBalance: 0,
  },
  {
    name: 'Ethan Hunt',
    phone: '555-0105',
    whatsapp: '555-0105',
    address: '221B Baker Street, London',
    openingBalance: 120.75,
    dueBalance: 120.75,
  },
];
